refactored code as per SOLID
ShridharDaga/task-list-kata pull request #1
Opened 2023-03-03 13:43 UTC by ShridharDaga

refactored code as per SOLID

2023-03-08 09:31 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/TaskAdd.java
> +public class TaskAdd {
add an interface for this class

2023-03-08 09:32 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/TaskAdd.java
> +    public long nextId() {
make this private

2023-03-08 09:34 UTC, AbhilashZemoso requested changes
work on comments

2023-03-08 11:27 UTC, ShridharDaga commented on java/src/main/java/com/codurance/training/tasks/TaskAdd.java
> +public class TaskAdd {
addressed

2023-03-08 11:27 UTC, ShridharDaga commented on java/src/main/java/com/codurance/training/tasks/TaskAdd.java
> +    public long nextId() {
addressed

2023-03-09 05:22 UTC, AbhilashZemoso approved these changes
LGTM

2023-03-09 06:11 UTC, merged